/**
 * This file is auto-generated by Scaffold-ETH deploy scripts.
 * After running `yarn deploy`, this will be populated with deployed contract addresses and ABIs.
 * For now, this is a placeholder that will be updated after deployment.
 */

const deployedContracts = {
  // Hardhat localhost (chain ID: 31337)
  31337: {
    FlowNFT: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3" as `0x${string}`,
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [{ name: "owner", type: "address" }],
          name: "hasMinted",
          outputs: [{ name: "", type: "bool" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ name: "owner", type: "address" }],
          name: "tokenOfOwner",
          outputs: [{ name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ name: "user", type: "address" }],
          name: "getFlowState",
          outputs: [
            { name: "currentEpoch", type: "uint256" },
            { name: "likesReceived", type: "uint256" },
            { name: "likesSent", type: "uint256" },
            { name: "tipsReceived", type: "uint256" },
            { name: "tipsSent", type: "uint256" },
            { name: "totalInteractions", type: "uint256" },
            { name: "stateLevel", type: "uint256" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ name: "user", type: "address" }],
          name: "getStateLevel",
          outputs: [{ name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ name: "tokenId", type: "uint256" }],
          name: "tokenURI",
          outputs: [{ name: "", type: "string" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "mint",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "getCurrentEpoch",
          outputs: [{ name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, name: "owner", type: "address" },
            { indexed: true, name: "tokenId", type: "uint256" },
          ],
          name: "NFTMinted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, name: "user", type: "address" },
            { indexed: false, name: "oldLevel", type: "uint256" },
            { indexed: false, name: "newLevel", type: "uint256" },
          ],
          name: "StateChanged",
          type: "event",
        },
      ] as const,
    },
    ActivityTracker: {
      address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as `0x${string}`,
      abi: [
        {
          inputs: [{ name: "_flowNFT", type: "address" }],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [{ name: "target", type: "address" }],
          name: "like",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ name: "targets", type: "address[]" }],
          name: "batchLike",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { name: "from", type: "address" },
            { name: "target", type: "address" },
          ],
          name: "hasLikedInEpoch",
          outputs: [{ name: "", type: "bool" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getCurrentEpoch",
          outputs: [{ name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, name: "from", type: "address" },
            { indexed: true, name: "to", type: "address" },
            { indexed: false, name: "epoch", type: "uint256" },
          ],
          name: "Liked",
          type: "event",
        },
      ] as const,
    },
    TipModule: {
      address: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0" as `0x${string}`,
      abi: [
        {
          inputs: [{ name: "_flowNFT", type: "address" }],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [{ name: "recipient", type: "address" }],
          name: "tip",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ name: "user", type: "address" }],
          name: "pendingWithdrawals",
          outputs: [{ name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ name: "user", type: "address" }],
          name: "totalTipsReceived",
          outputs: [{ name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ name: "user", type: "address" }],
          name: "totalTipsSent",
          outputs: [{ name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { name: "recipients", type: "address[]" },
            { name: "amounts", type: "uint256[]" },
          ],
          name: "batchTip",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "MIN_TIP_AMOUNT",
          outputs: [{ name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, name: "from", type: "address" },
            { indexed: true, name: "to", type: "address" },
            { indexed: false, name: "amount", type: "uint256" },
            { indexed: false, name: "epoch", type: "uint256" },
          ],
          name: "Tipped",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, name: "user", type: "address" },
            { indexed: false, name: "amount", type: "uint256" },
          ],
          name: "Withdrawn",
          type: "event",
        },
      ] as const,
    },
  },
  // Monad Testnet (chain ID: 10143)
  10143: {
    FlowNFT: {
      address: "0x0000000000000000000000000000000000000000" as `0x${string}`,
      abi: [] as const,
    },
    ActivityTracker: {
      address: "0x0000000000000000000000000000000000000000" as `0x${string}`,
      abi: [] as const,
    },
    TipModule: {
      address: "0x0000000000000000000000000000000000000000" as `0x${string}`,
      abi: [] as const,
    },
  },
} as const;

export default deployedContracts;
